### ISSUE TITLE
Code is always -1000

### ISSUE THREAD

**Issue by stefdelec** [vphantom/js-jrpc#14]
Hi,

I created a helloworld: 
```

const rpc = new JRPC({remoteTimeout:10});

rpc.expose("foo", function(params, next) {
    console.log("fooo called")
  return next(false);
});

rpc.call("foo", {},function(err, result) {
    if (err) {
        console.log(err)
      // Something went wrong...
    } else {
        console.log('success')
      // 'result' was returned by the other end's exposed 'foo()'
    }
  }
  );
```

And I always got { code: -1000, message: 'Timed out waiting for response' }.
Am I missing something?

Thanks,

**Comment by vphantom** [comment]
The JRPC module represents the services of a remote server, so it's normal that you can't call your own side's `foo()` in the above. And because it's not connected to a remote service, the RPC call immediately fails because it has nowhere to send the request to.

That said, it would be nice if the library gave you a more explicit error code in this case, because a timeout makes no sense when there is no connection to begin with.  I'll look into that.

**Comment by vphantom** [comment]
Hi again,

Version 3.1.3 is out (given about an hour for NPM to update).  Now when `.setTransmitter()` was not yet called when a remote call deadline times out, the call will return a specific `-1100` error instead, to clarify this situation.
